apiVersion: v1
kind: Service
metadata:
  name: flask-demo-helm
  labels:
    app: flask-demo-helm
    version: v1
spec:
  ports:
    - name: http-5000
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.target_port }}
  selector:
    app: flask-demo-helm
    version: v1
  type: {{ .Values.service.type }}
