---
# Source: eck-stack/charts/eck-elasticsearch/templates/elasticsearch.yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  labels:
    helm.sh/chart: eck-elasticsearch-0.6.0
    app.kubernetes.io/name: eck-elasticsearch
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
  annotations:
    eck.k8s.elastic.co/license: enterprise
spec:
  version: 8.8.0
  nodeSets:

    - config:
        node.store.allow_mmap: false
      count: 1
      name: default
      podTemplate:
        spec:
          containers:
          - name: elasticsearch
            resources:
              limits:
                memory: 1Gi
              requests:
                memory: 1Gi
          volumes:
          - emptyDir: {}
            name: elasticsearch-data
---
# Source: eck-stack/charts/eck-kibana/templates/kibana.yaml
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: release-name-eck-kibana
  labels:
    helm.sh/chart: eck-kibana-0.6.0
    app.kubernetes.io/name: eck-kibana
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
  annotations:
    eck.k8s.elastic.co/license: enterprise
spec:
  version: 8.8.0
  count: 1
  elasticsearchRef:
    name: elasticsearch
