---
# Source: eck-elasticsearch/templates/elasticsearch.yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: release-name-eck-elasticsearch
  labels:
    helm.sh/chart: eck-elasticsearch-0.6.0
    app.kubernetes.io/name: eck-elasticsearch
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
  annotations:
    eck.k8s.elastic.co/license: enterprise
spec:
  version: 8.8.0
  nodeSets:

    - config:
        node.store.allow_mmap: false
      count: 1
      name: default
      podTemplate:
        spec:
          containers:
          - name: elasticsearch
            resources:
              limits:
                memory: 2Gi
              requests:
                memory: 2Gi
        volumes:
        - emptyDir: {}
          name: elasticsearch-data
